"""add custom_name column to conversations table

Revision ID: 0abafbc6a8f1
Revises: 9fb10fc3827d
Create Date: 2026-02-25 00:07:38.086896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abafbc6a8f1'
down_revision: Union[str, Sequence[str], None] = '9fb10fc3827d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('custom_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'custom_name')
    # ### end Alembic commands ###
