"""create user_skill_autoloads table

Revision ID: 503d2eb4046f
Revises: 92ea0f869803
Create Date: 2026-03-24 17:56:52.049192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503d2eb4046f'
down_revision: Union[str, Sequence[str], None] = '92ea0f869803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skill_autoloads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_skill_autoloads_skill_id', 'user_skill_autoloads', ['skill_id'], unique=False)
    op.create_index('ix_user_skill_autoloads_user_id', 'user_skill_autoloads', ['user_id'], unique=False)
    op.create_index('ix_user_skill_autoloads_user_id_skill_id', 'user_skill_autoloads', ['user_id', 'skill_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_skill_autoloads_user_id_skill_id', table_name='user_skill_autoloads')
    op.drop_index('ix_user_skill_autoloads_user_id', table_name='user_skill_autoloads')
    op.drop_index('ix_user_skill_autoloads_skill_id', table_name='user_skill_autoloads')
    op.drop_table('user_skill_autoloads')
    # ### end Alembic commands ###
