"""create action_requests table

Revision ID: 579f8092da31
Revises: a7eb1d002df0
Create Date: 2026-03-02 19:55:27.942107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579f8092da31'
down_revision: Union[str, Sequence[str], None] = 'a7eb1d002df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_requests_conversation_id', 'action_requests', ['conversation_id'], unique=False)
    op.create_index('ix_action_requests_user_id', 'action_requests', ['user_id'], unique=False)
    op.create_index('ix_action_requests_user_id_status', 'action_requests', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_action_requests_user_id_status', table_name='action_requests')
    op.drop_index('ix_action_requests_user_id', table_name='action_requests')
    op.drop_index('ix_action_requests_conversation_id', table_name='action_requests')
    op.drop_table('action_requests')
    # ### end Alembic commands ###
