"""create gemini_api_calls table for token usage tracking

Revision ID: 7d31c3fd5c83
Revises: 0abafbc6a8f1
Create Date: 2026-02-25 20:54:40.128405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d31c3fd5c83'
down_revision: Union[str, Sequence[str], None] = '0abafbc6a8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemini_api_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gemini_api_calls_conversation_id', 'gemini_api_calls', ['conversation_id'], unique=False)
    op.create_index('ix_gemini_api_calls_created_at', 'gemini_api_calls', ['created_at'], unique=False)
    op.create_index('ix_gemini_api_calls_user_id', 'gemini_api_calls', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gemini_api_calls_user_id', table_name='gemini_api_calls')
    op.drop_index('ix_gemini_api_calls_created_at', table_name='gemini_api_calls')
    op.drop_index('ix_gemini_api_calls_conversation_id', table_name='gemini_api_calls')
    op.drop_table('gemini_api_calls')
    # ### end Alembic commands ###
