"""create skills and skill_shares tables

Revision ID: 92ea0f869803
Revises: a3c7e9f12b4d
Create Date: 2026-03-23 19:52:10.713803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ea0f869803'
down_revision: Union[str, Sequence[str], None] = 'a3c7e9f12b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_creator_id'), 'skills', ['creator_id'], unique=False)
    op.create_index('ix_skills_creator_id_name', 'skills', ['creator_id', 'name'], unique=True)
    op.create_index('ix_skills_visibility', 'skills', ['visibility'], unique=False)
    op.create_table('skill_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_shares_skill_id', 'skill_shares', ['skill_id'], unique=False)
    op.create_index('ix_skill_shares_skill_id_user_id', 'skill_shares', ['skill_id', 'user_id'], unique=True)
    op.create_index('ix_skill_shares_user_id', 'skill_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skill_shares_user_id', table_name='skill_shares')
    op.drop_index('ix_skill_shares_skill_id_user_id', table_name='skill_shares')
    op.drop_index('ix_skill_shares_skill_id', table_name='skill_shares')
    op.drop_table('skill_shares')
    op.drop_index('ix_skills_visibility', table_name='skills')
    op.drop_index('ix_skills_creator_id_name', table_name='skills')
    op.drop_index(op.f('ix_skills_creator_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
