"""create memories table

Revision ID: 94c49d92fea7
Revises: 39b5019459c4
Create Date: 2026-02-11 21:40:09.862344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c49d92fea7'
down_revision: Union[str, Sequence[str], None] = '39b5019459c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_user_email'), 'memories', ['user_email'], unique=False)
    # ### end Alembic commands ###

    # FTS5 virtual table for full-text search on memory content
    op.execute("""
        CREATE VIRTUAL TABLE memories_fts USING fts5(
            content,
            content='memories',
            content_rowid='rowid'
        );
    """)

    # Triggers to keep FTS index in sync with the memories table
    op.execute("""
        CREATE TRIGGER memories_ai AFTER INSERT ON memories BEGIN
            INSERT INTO memories_fts(rowid, content)
            VALUES (NEW.rowid, NEW.content);
        END;
    """)
    op.execute("""
        CREATE TRIGGER memories_ad AFTER DELETE ON memories BEGIN
            INSERT INTO memories_fts(memories_fts, rowid, content)
            VALUES ('delete', OLD.rowid, OLD.content);
        END;
    """)
    op.execute("""
        CREATE TRIGGER memories_au AFTER UPDATE ON memories BEGIN
            INSERT INTO memories_fts(memories_fts, rowid, content)
            VALUES ('delete', OLD.rowid, OLD.content);
            INSERT INTO memories_fts(rowid, content)
            VALUES (NEW.rowid, NEW.content);
        END;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop FTS5 triggers and virtual table before dropping the memories table
    op.execute("DROP TRIGGER IF EXISTS memories_au;")
    op.execute("DROP TRIGGER IF EXISTS memories_ad;")
    op.execute("DROP TRIGGER IF EXISTS memories_ai;")
    op.execute("DROP TABLE IF EXISTS memories_fts;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_user_email'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
