"""Seccomp profile for the script-runner sandbox: no symlink creation.

The sandbox bind-mounts the conversation workspace read-write, so a symlink
created inside the container lands on the host filesystem. Host-side
workspace consumers (folder zip downloads, workspace duplication and moves,
uploads) operate on those entries with the server's privileges, so a symlink
pointing outside the workspace would let sandbox code read or overwrite any
file reachable by the service user. Nothing else in the system writes
symlinks into workspaces (uploads store raw bytes, there is no host-side
archive extraction), which makes the container boundary the single place
where the whole class can be killed: deny the ``symlink`` and ``symlinkat``
syscalls with EPERM. That also covers indirect creators inside the
container, e.g. ``ln -s`` or ``unzip`` extracting an archive that contains
symlink entries.

The profile is derived from the host's default containers seccomp profile
(``/etc/containers/seccomp.json``, then ``/usr/share/containers/seccomp.json``)
rather than a minimal default-allow profile so the rest of the default
confinement is preserved -- notably the ``io_uring_*`` denial, without which
``IORING_OP_SYMLINKAT`` could create symlinks past a syscall filter -- and
stays current with distro updates. The vendored snapshot
``script-runner-seccomp-fallback.json`` (repo root) covers hosts without a
readable default profile.

The patched profile is written to ``<data_dir>/sandbox-seccomp.json`` and
handed to podman via ``--security-opt=seccomp=...`` by
``_build_script_podman_cmd``; a failure to build it fails the sandbox run
(fail closed) rather than running an unconfined container.
"""

import errno
import json
import logging
import os
from pathlib import Path

from config import paths

logger = logging.getLogger(__name__)

# Syscalls that create symbolic links. Hardlinks (link/linkat) stay allowed:
# only the workspace mount and the container image's own overlay are visible
# in the mount namespace, so a hardlink can never reference an unmounted
# host path (and cross-filesystem links fail with EXDEV anyway).
BLOCKED_SYSCALLS = ("symlink", "symlinkat")

# Standard locations of the containers-common default profile, in podman's
# own lookup order.
_DEFAULT_PROFILE_PATHS = (
    Path("/etc/containers/seccomp.json"),
    Path("/usr/share/containers/seccomp.json"),
)

# Vendored snapshot of the containers-common default profile, used when no
# host default is readable.
FALLBACK_PROFILE = paths.PROJECT_ROOT / "script-runner-seccomp-fallback.json"

# Cache: output path already generated by this process. Regeneration happens
# once per process so a deploy with changed patch logic (or a distro profile
# update) is picked up on restart; keyed by the output path so tests that
# repoint DATA_DIR regenerate.
_generated: Path | None = None


def _load_source_profile() -> dict:
    """Load the first usable base profile (host defaults, then vendored)."""
    for candidate in (*_DEFAULT_PROFILE_PATHS, FALLBACK_PROFILE):
        try:
            with open(candidate, "r") as f:
                profile = json.load(f)
        except FileNotFoundError:
            continue
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("Skipping unusable seccomp profile %s: %s", candidate, exc)
            continue
        if (
            isinstance(profile, dict)
            and profile.get("defaultAction")
            and isinstance(profile.get("syscalls"), list)
        ):
            return profile
        logger.warning("Skipping malformed seccomp profile %s", candidate)
    raise RuntimeError(
        "No usable base seccomp profile found for the script sandbox "
        "(checked /etc/containers/seccomp.json, "
        "/usr/share/containers/seccomp.json, and the vendored fallback)"
    )


def _patch_profile(profile: dict) -> None:
    """Rewrite ``profile`` in place so the blocked syscalls fail with EPERM.

    The syscall names are removed from every existing group first (libseccomp
    rejects conflicting unconditional rules for the same syscall), then a
    single explicit ERRNO group is appended. Groups left empty by the
    removal are dropped.
    """
    blocked = set(BLOCKED_SYSCALLS)
    groups = profile.get("syscalls") or []
    for group in groups:
        names = group.get("names")
        if isinstance(names, list):
            group["names"] = [n for n in names if n not in blocked]
    profile["syscalls"] = [g for g in groups if g.get("names")]
    profile["syscalls"].append({
        "names": sorted(blocked),
        "action": "SCMP_ACT_ERRNO",
        "errnoRet": errno.EPERM,
        "args": [],
        "comment": (
            "Quest: the workspace mount is host-backed; symlink creation "
            "is banned in the sandbox"
        ),
        "includes": {},
        "excludes": {},
    })


def get_sandbox_seccomp_profile_path() -> Path:
    """Return the path of the patched sandbox seccomp profile.

    Generates ``<data_dir>/sandbox-seccomp.json`` on first use per process
    (atomic write). Fully synchronous so concurrent tool calls on the single
    server event loop cannot interleave the generate-and-write.

    Raises:
        RuntimeError: If no base profile could be loaded. Callers must
            treat this as fatal for the sandbox run -- never fall back to
            running the container without the profile.
    """
    global _generated
    out_path = paths.DATA_DIR / "sandbox-seccomp.json"
    if _generated == out_path and out_path.is_file():
        return out_path

    profile = _load_source_profile()
    _patch_profile(profile)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = out_path.with_name(out_path.name + ".tmp")
    with open(tmp_path, "w") as f:
        json.dump(profile, f, indent=2)
    os.replace(tmp_path, out_path)

    _generated = out_path
    return out_path
